name: Test Send Message

on: 
  workflow_dispatch:
    inputs:
      DEVICE_NAME:
        description: 'Enter Your Recovery.img url'
        required: false

jobs:
  OrangeFox-Build:
    name: Build OFOX by ${{ github.actor }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Upload files to Telegram
      run: |
        sudo apt update -y && sudo apt install wget pip python3 -y

    - name: start
      run: |
        wget -O recovery.img $DEVICE_NAME
        pip install twrpdtgen --break-system-packages
        python3 -m twrpdtgen
