name: OrangeFox - Build

on:
  workflow_dispatch:
    inputs:
      RECOVERY_NAME:
        description: 'Select Recovery To Build'
        required: true
        default: 'OFOX'
        type: choice
        options:
        - TWRP
        - OFOX
        - PBRP
        - SHRP
      MANIFEST_BRANCH:
        description: 'Recovery Manifest Branch'
        required: true
        default: '12.1'
        type: choice
        options:
        - 12.1
        - 11.0
      DEVICE_TREE:
        description: 'Recovery Device Tree'
        required: true
        default: 'https://github.com/cd-Crypton/custom_recovery_tree_realme_nashc'
      DEVICE_TREE_BRANCH:
        description: 'Recovery Device Tree Branch'
        required: true
        default: 'android-12.1'
      DEVICE_PATH:
        description: 'Specify your Device Path'
        required: true
        default: 'device/realme/nashc'
      DEVICE_NAME:
        description: 'Specify your Device Codename'
        required: true
        default: 'nashc'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendor_boot
      SEND_TELEGRAM:
        description: 'Auto Send To Telegram'
        required: false
        default: true
        type: boolean

jobs:
  OrangeFox-Build:
    name: Build OFR by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.RECOVERY_NAME == 'OFOX' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check secrets
      id: check
      run: |
        if [[ -z "${{ secrets.CHAT_ID }}" ]]; then
          echo "Build Failed, CHAT_ID not set!"
          exit 1
        fi

        if [[ -z "${{ secrets.BOT_TOKEN }}" ]]; then
          echo "Build Failed, BOT_TOKEN not set!"
          exit 1
        fi
        
    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 15
      
    - name: Build Environment
      run: |
        sudo apt install aria2 -y
        git clone https://gitlab.com/OrangeFox/misc/scripts.git -b master
        cd scripts
        sudo bash setup/android_build_env.sh
      
    - name: Set-up Manifest
      if: github.event.inputs.MANIFEST_BRANCH == '11.0' || github.event.inputs.MANIFEST_BRANCH == '12.1'
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
        cd ${GITHUB_WORKSPACE}/OrangeFox
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.build"
        git clone https://gitlab.com/OrangeFox/sync.git -b master
        cd sync
        ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}

    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
        cd ${{ github.event.inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Building OrangeFox
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        set +e
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        set -e
        lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng && make clean && mka adbd ${{ github.event.inputs.BUILD_TARGET }}image

    - name: Set Release Properties
      run: |
        echo "BUILD_DATE=$(TZ=Asia/Jakarta date +%Y%m%d)" >> $GITHUB_ENV
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}

    - name: Upload files to Telegram
      if: github.event.inputs.SEND_TELEGRAM == 'true'
      uses: appleboy/telegram-action@master
      with:
        to: ${{  secrets.CHAT_ID  }}
        token: ${{ secrets.BOT_TOKEN }}
        message: "
          <pre>
              <b>OrangeFox Recovery - Unofficial</b>
              <b>Devices : ${{ github.event.inputs.DEVICE_NAME }}</b>
              <b>Build Date : ${{ env.BUILD_DATE }}</b>
          </pre> "
        document: |
          ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img
          ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.zip
     
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img
          OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.zip
        name: OrangeFox Recovery for ${{ github.event.inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          ## OrangeFox Recovery - Unofficial
          Devices : ${{ github.event.inputs.DEVICE_NAME }}
          Build Date : ${{ env.BUILD_DATE }}
